USE [FECertASESYS]
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'01', N'VENTAS EN PESOS CREDITO Y CONTADO
                                                                                                                   ', NULL, NULL, N'TRANSA01                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N'', N'vFEVentaRD                                                                                          ', NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'02', N'VENTAS EN DOLARES CREDITO Y CONTADO
                                                                                                                 ', NULL, NULL, N'TRANSA01                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', N'vFEVentaUS                                                                                          ', NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'03', N'DEVOLUCION DE CONTADO PESOS
                                                                                                                         ', NULL, NULL, N'TRANSA01                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', N'vFEDevCORD                                                                                          ', NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'04', N'DEVOLUCION DE CONTADO DOLARES
                                                                                                                       ', NULL, NULL, N'TRANSA01                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', N'vFEDevCOUS                                                                                          ', NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'05', N'DEVOLUCION DE CREDITO PESOS
                                                                                                                         ', NULL, NULL, N'TRANSA01                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', N'vFEDevCRRD                                                                                          ', NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'06', N'DEVOLUCION DE CREDITO DOLARES
                                                                                                                       ', NULL, NULL, N'TRANSA01                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', N'vFEDevCRUS                                                                                          ', NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'07', N'NOTA DE CREDITO DIRECTA PESOS
                                                                                                                       ', NULL, NULL, N'CXCMOVI1                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', N'vFENCDIRD                                                                                           ', NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'08', N'NOTA DE CREDITO DIRECTA DOLARES
                                                                                                                     ', NULL, NULL, N'CXCMOVI1                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', N'vFENCDIUS                                                                                           ', NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'09', N'PROVEEDOR INFORMAL PESOS
                                                                                                                            ', NULL, NULL, N'CXPMOVI1                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'10', N'GASTOS MENORES
                                                                                                                                      ', NULL, NULL, N'CAJACHICA                                                                                           ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'11', N'NOTA DE DEBITO PESOS
                                                                                                                                ', NULL, NULL, N'CXCMOVI1                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[movife] ([IDFE], [Descripcion], [Movimiento], [TiposComprobantesUtilizados], [TablaOrigen], [CampoFiltro1], [CampoFiltro2], [QueryEncabezado], [NombreQueryEncabezado], [QueryDetalle], [NombreQueryDetalle], [Observaciones]) VALUES (N'12', N'NOTA DE DEBITO DOLARES
                                                                                                                              ', NULL, NULL, N'CXCMOVI1                                                                                            ', N'RNCEMISOR                                                                                           ', N'ncf                                                                                                 ', N' ', NULL, NULL, NULL, NULL)
GO
