create or alter view VFEDetalleCajaChica as

SELECT 

    NULL AS NumeroLinea,
    max(cc.documento) AS NumeroFacturaInterna,
    max(cc.ncftipo) AS TipoDocumento,
    max(SUBSTRING (cc.ncf, 2, 2)) AS TipoECF,
    max(SUBSTRING (cc.ncf, 1, 1)) AS TipoECFL,
	cc.ncf as eNCF,
	cc.RNCEmisor,
    CAST('Interno' AS CHAR(100)) AS TipoCodigo1,
    CAST(max(cc.cuenta) AS CHAR(100)) AS CodigoItem1,
    CAST('' AS CHAR(100)) AS TipoCodigo2,
    CAST('' AS CHAR(100)) AS CodigoItem2,
    CAST('' AS CHAR(100)) AS TipoCodigo3,
    CAST('' AS CHAR(100)) AS CodigoItem3,
    CAST('' AS CHAR(100)) AS TipoCodigo4,
    CAST('' AS CHAR(100)) AS CodigoItem4,
    CAST('' AS CHAR(100)) AS TipoCodigo5,
    CAST('' AS CHAR(100)) AS CodigoItem5,
    4 AS IndicadorFacturacion,
    max(i.Siglas) AS SiglasImpuesto,
    max(i.Descrip) AS DescripcionImpuesto,
    NULL AS IndicadorAgenteRetencionoPercepcion,
    NULL AS MontoITBISRetenido,
    NULL AS MontoISRRetenido,
    max(cc.DESCRIP) NombreItem,
    1 AS IndicadorBienoServicio,
    NULL AS DescripcionItem,
    1 AS CantidadItem,
    '43' AS UnidadMedida,
    NULL AS CantidadReferencia,
    NULL AS UnidadReferencia,
    NULL AS Subcantidad1,
    NULL AS CodigoSubcantidad1,
    NULL AS Subcantidad2,
    NULL AS CodigoSubcantidad2,
    NULL AS Subcantidad3,
    NULL AS CodigoSubcantidad3,
    NULL AS Subcantidad4,
    NULL AS CodigoSubcantidad4,
    NULL AS Subcantidad5,
    NULL AS CodigoSubcantidad5,
    NULL AS GradosAlcohol,
    NULL AS PrecioUnitarioReferencia,
    NULL AS FechaElaboracion,
    NULL AS FechaVencimientoItem,
    NULL AS PesoNetoKilogramo,
    NULL AS PesoNetoMineria,
    NULL AS TipoAfiliacion,
    NULL AS Liquidacion,
    SUM(cc.debito - cc.credito) AS PrecioUnitarioItem,
    NULL AS DescuentoMonto,
    0 AS TasaITBIS,
    1 AS IndicadorMontoGravado,
    NULL AS MontoITBIS,
    NULL AS TasaDescuento,
    '' AS TipoSubDescuento1,
    NULL AS SubDescuentoPorcentaje1,
    NULL AS MontoSubDescuento1,
    NULL AS TipoSubDescuento2,
    NULL AS SubDescuentoPorcentaje2,
    NULL AS MontoSubDescuento2,
    NULL AS TipoSubDescuento3,
    NULL AS SubDescuentoPorcentaje3,
    NULL AS MontoSubDescuento3,
    NULL AS TipoSubDescuento4,
    NULL AS SubDescuentoPorcentaje4,
    NULL AS MontoSubDescuento4,
    NULL AS TipoSubDescuento5,
    NULL AS SubDescuentoPorcentaje5,
    NULL AS MontoSubDescuento5,
    NULL AS MontoRecargo,
    NULL AS TipoSubRecargo1,
    NULL AS SubRecargoPorcentaje1,
    NULL AS MontoSubRecargo1,
    NULL AS TipoSubRecargo2,
    NULL AS SubRecargoPorcentaje2,
    NULL AS MontoSubRecargo2,
    NULL AS TipoSubRecargo3,
    NULL AS SubRecargoPorcentaje3,
    NULL AS MontoSubRecargo3,
    NULL AS TipoSubRecargo4,
    NULL AS SubRecargoPorcentaje4,
    NULL AS MontoSubRecargo4,
    NULL AS TipoSubRecargo5,
    NULL AS SubRecargoPorcentaje5,
    NULL AS MontoSubRecargo5,
    NULL AS TipoImpuesto1,
    NULL AS TipoImpuesto2,
    1 AS TipoCambio,
    NULL AS MontoITBISOtraMoneda,
    NULL AS PrecioOtraMoneda,
    NULL AS DescuentoOtraMoneda,
    NULL AS MontoRecargoOtraMoneta,
    NULL AS MontoItemOtraMoneda,
    SUM(cc.debito - cc.credito) AS MontoItem,
    MAX(cc.EstadoFiscal) as EstadoFiscal,
    MAX(cc.Trackid) as Trackid,
    MAX(cc.FechaFirma) as FechaFirma,
    MAX(cc.CodigoSeguridad) as CodigoSeguridad,
    MAX(cc.Estadoimpresion) as Estadoimpresion,
    NULL AS ConteoImpresiones,
	'' AS NotaImpresion
FROM cajachica cc
LEFT OUTER JOIN dbo.impuesto AS i ON i.impuesto = '00'
WHERE cc.ncftipo IN ('GM') 
    AND (cc.ncf IS NOT NULL) 
    AND (cc.ncf <> '') 
    AND (cc.EstadoFiscal IS NOT NULL)
GROUP BY 
    cc.RNCEmisor,
    cc.ncf



