CREATE OR ALTER VIEW   vFEEncabezado AS 

WITH
 e AS (
    SELECT top 1
      itbisenprecio,
      trim(rnc)   as rnc ,
	  ambiente,
	  nota
    FROM empresa WITH (NOLOCK)
  ), 
 AmbienteInfo AS ( Select top 1
        A.AMBIENTE   as AMBIENTE, 
        A.DESCRIP   as DESCRIP, 
        ISNULL(A.RUTA, '')  AS RUTA 
    FROM FEAmbiente A WITH (NOLOCK)
	LEFT JOIN e WITH (NOLOCK) on  a.ambiente = e.ambiente 
    WHERE A.RUTA IS NOT NULL
	and a.ambiente = e.ambiente
),

Totales AS (
	SELECT 
        rncemisor,encf,
		SUM(MontoTotal)-sum(MontoImpuesto)-SUM(CASE WHEN IndicadorFacturacion = 4 THEN MontoTotal-MontoImpuesto ELSE 0 END) as MontoGravadoTotal,
		SUM(CASE WHEN IndicadorFacturacion = 4 THEN MontoTotal-MontoImpuesto ELSE 0 END) AS MontoExento,
		SUM(MontoImpuesto) as TotalITBIS,

		MAX(CASE WHEN IndicadorFacturacion = 0 THEN 1 ELSE 0 END) AS IndicadorMontoGravadoINF,
		MAX(CASE WHEN IndicadorFacturacion = 1 THEN 1 ELSE 0 END) AS IndicadorMontoGravadoI18,
		MAX(CASE WHEN IndicadorFacturacion = 2 THEN 1 ELSE 0 END) AS IndicadorMontoGravadoI16,
		MAX(CASE WHEN IndicadorFacturacion = 3 THEN 1 ELSE 0 END) AS IndicadorMontoGravadoIEX,
		MAX(CASE WHEN IndicadorFacturacion = 4 THEN 1 ELSE 0 END) AS IndicadorMontoGravadoIE,

		SUM(CASE WHEN IndicadorFacturacion = 0 THEN MontoTotal-MontoImpuesto ELSE 0 END) AS MontoGravadoINF,
		SUM(CASE WHEN IndicadorFacturacion = 1 THEN MontoTotal-MontoImpuesto ELSE 0 END) AS MontoGravadoI18,
		SUM(CASE WHEN IndicadorFacturacion = 2 THEN MontoTotal-MontoImpuesto ELSE 0 END) AS MontoGravadoI16,
		SUM(CASE WHEN IndicadorFacturacion = 3 THEN MontoTotal-MontoImpuesto ELSE 0 END) AS MontoGravadoIEX,
		SUM(CASE WHEN IndicadorFacturacion = 4 THEN MontoTotal-MontoImpuesto ELSE 0 END) AS MontoGravadoIE,

		MAX(CASE WHEN IndicadorFacturacion = 1 THEN 18 ELSE 0 END) AS ITBIS1,
		MAX(CASE WHEN IndicadorFacturacion = 2 THEN 16 ELSE 0 END) AS ITBIS2,
		MAX(CASE WHEN IndicadorFacturacion = 3 THEN 0 ELSE 0 END) AS ITBIS3,

		SUM(CASE WHEN IndicadorFacturacion = 1 THEN MontoImpuesto ELSE 0 END) AS TotalITBIS1,
		SUM(CASE WHEN IndicadorFacturacion = 2 THEN MontoImpuesto ELSE 0 END) AS TotalITBIS2,
		SUM(CASE WHEN IndicadorFacturacion = 3 THEN MontoImpuesto ELSE 0 END) AS TotalITBIS3,

		0 AS MontoImpuestoAdicional
	FROM
		(
		Select   
			rncemisor,encf, IndicadorFacturacion,
			sum(COALESCE(MontoItem*(i.tasa/100), 0 )) as MontoImpuesto,
			sum(COALESCE(MontoItem, 0 )) AS MontoTotal
		from  vfedetalle AS det WITH (NOLOCK)
		LEFT OUTER JOIN dbo.itbisdgii AS i WITH (NOLOCK) ON i.codigo = det.IndicadorFacturacion
		group by rncemisor,encf, IndicadorFacturacion
		) AS SubConsulta
	GROUP BY rncemisor,encf

)

SELECT
  SUBSTRING(enc.eNCF, 2, 2) as TipoECF,
  SUBSTRING(enc.eNCF, 1, 1) as TipoECFL,
  enc.eNCF,
  'feencabezado' as Tabla,
  'rncemisor' as campo1,
  'encf' as campo2,
  enc.FechaVencimientoSecuencia,
  enc.IndicadorNotaCredito,
  enc.IndicadorEnvioDiferido,
  enc.IndicadorMontoGravado,
  enc.TipoIngresos,
  enc.TipoPago,
  enc.FechaLimitePago,
  enc.TerminoPago,
  enc.FormaPago1,
  enc.MontoPago1,
  enc.FormaPago2,
  enc.MontoPago2,
  enc.FormaPago3,
  enc.MontoPago3,
  enc.FormaPago4,
  enc.MontoPago4,
  enc.FormaPago5,
  enc.MontoPago5,
  enc.FormaPago6,
  enc.MontoPago6,
  enc.FormaPago7,
  enc.MontoPago7,
  enc.TipoCuentaPago,
  enc.NumeroCuentaPago,
  enc.BancoPago,
  enc.FechaDesde,
  enc.FechaHasta,
  enc.TotalPaginas,
  enc.RNCEmisor,
  enc.RazonSocialEmisor,
  enc.NombreComercial,
  enc.Sucursal,
  enc.DireccionEmisor,
  enc.Municipio,
  enc.Provincia,
  enc.TelefonoEmisor1,
  enc.TelefonoEmisor2,
  enc.TelefonoEmisor3,
  enc.CorreoEmisor,
  enc.WebSite,
  enc.ActividadEconomica,
  enc.CodigoVendedor,
  enc.NumeroFacturaInterna,
  enc.NumeroPedidoInterno,
  enc.ZonaVenta,
  enc.RutaVenta,
  enc.InformacionAdicionalEmisor,
  enc.FechaEmision,
  enc.RNCComprador,
  enc.IdentificadorExtranjero,
  enc.RazonSocialComprador,
  enc.ContactoComprador,
  enc.CorreoComprador,
  enc.DireccionComprador,
  enc.MunicipioComprador,
  enc.ProvinciaComprador,
  enc.PaisComprador,
  enc.FechaEntrega,
  enc.ContactoEntrega,
  enc.DireccionEntrega,
  enc.TelefonoAdicional,
  enc.FechaOrdenCompra,
  enc.NumeroOrdenCompra,
  enc.CodigoInternoComprador,
  enc.ResponsablePago,
  enc.Informacionadicionalcomprador,
  enc.FechaEmbarque,
  enc.NumeroEmbarque,
  enc.NumeroContenedor,
  enc.NumeroReferencia,
  enc.NombrePuertoEmbarque,
  enc.CondicionesEntrega,
  enc.TotalFob,
  enc.Seguro,
  enc.Flete,
  enc.OtrosGastos,
  enc.TotalCif,
  enc.RegimenAduanero,
  enc.NombrePuertoSalida,
  enc.NombrePuertoDesembarque,
  enc.PesoBruto,
  enc.PesoNeto,
  enc.UnidadPesoBruto,
  enc.UnidadPesoNeto,
  enc.CantidadBulto,
  enc.UnidadBulto,
  enc.VolumenBulto,
  enc.UnidadVolumen,
  enc.ViaTransporte,
  enc.PaisOrigen,
  enc.DireccionDestino,
  enc.PaisDestino,
  enc.RNCIdentificacionCompaniaTransportista,
  enc.NombreCompaniaTransportista,
  enc.NumeroViaje,
  enc.Conductor,
  enc.DocumentoTransporte,
  enc.Ficha,
  enc.Placa,
  enc.RutaTransporte,
  enc.ZonaTransporte,
  enc.NumeroAlbaran,


  Totales.IndicadorMontoGravadoINF,
  Totales.IndicadorMontoGravadoI18,
  Totales.IndicadorMontoGravadoI16,
  Totales.IndicadorMontoGravadoIEX,
  Totales.IndicadorMontoGravadoIE as IndicadorMontoGravadoI0, 
  Totales.IndicadorMontoGravadoIE,
  
  (Totales.MontoGravadoI18+Totales.MontoGravadoI16+Totales.MontoGravadoIE) as MontoGravadoTotal,

  Totales.MontoGravadoI18 as MontoGravadoI1,
  Totales.MontoGravadoI16 as MontoGravadoI2,
  Totales.MontoGravadoIEX AS MontoGravadoI3,
  case
  when IndicadorMontoGravadoIE = 1 then MontoGravadoIE 
  else null 
  end
  as MontoExento,
  (case
  when Totales.IndicadorMontoGravadoI18 = 1 then 18
  else Null
  end) as  ITBIS1,
    (case
  when Totales.IndicadorMontoGravadoI16 = 1 then 16
  else Null
  end) as  ITBIS2,
  (case
  when Totales.IndicadorMontoGravadoIE = 1 then 0
  else Null
  end) as  ITBIS3,

  enc.TotalITBIS,

 
  (case
  when Totales.IndicadorMontoGravadoI18 = 1 then (Totales.MontoGravadoI18*(18.0/100))
  else Null
  end) as  TotalITBIS1,
    (case
  when Totales.IndicadorMontoGravadoI16 = 1 then (Totales.MontoGravadoI16*(16.0/100))
  else Null
  end) as  TotalITBIS2,
  (case
  when Totales.IndicadorMontoGravadoIE = 1 then (Totales.MontoGravadoIEX*(0))
  else Null
  end) as  TotalITBIS3,
  
  enc.MontoImpuestoAdicional,
  enc.TipoImpuesto1,
  enc.TasaImpuestoAdicional1,
  enc.MontoImpuestoSelectivoConsumoEspecifico1,
  enc.MontoImpuestoSelectivoConsumoAdvalorem1,
  enc.OtrosImpuestosAdicionales1,
  enc.TipoImpuesto2,
  enc.TasaImpuestoAdicional2,
  enc.MontoImpuestoSelectivoConsumoEspecifico2,
  enc.MontoImpuestoSelectivoConsumoAdvalorem2,
  enc.OtrosImpuestosAdicionales2,
  enc.TipoImpuesto3,
  enc.TasaImpuestoAdicional3,
  enc.MontoImpuestoSelectivoConsumoEspecifico3,
  enc.MontoImpuestoSelectivoConsumoAdvalorem3,
  enc.OtrosImpuestosAdicionales3,
  enc.TipoImpuesto4,
  enc.TasaImpuestoAdicional4,
  enc.MontoImpuestoSelectivoConsumoEspecifico4,
  enc.MontoImpuestoSelectivoConsumoAdvalorem4,
  enc.OtrosImpuestosAdicionales4,
	Totales.MontoGravadoINF+(Totales.MontoGravadoINF*0)+
	Totales.MontoGravadoI18+(Totales.MontoGravadoI18*(18.0/100))+
	Totales.MontoGravadoI16+(Totales.MontoGravadoI16*(16.0/100))+
	Totales.MontoGravadoIEX+(Totales.MontoGravadoIEX*0)+
	Totales.MontoGravadoIE+(Totales.MontoGravadoIE*0) as MontoTotal,
  enc.MontoNoFacturable,
  enc.MontoPeriodo,
  enc.SaldoAnterior,
  enc.MontoAvancePago,
  enc.ValorPagar,
  enc.TotalITBISRetenido,
  enc.TotalISRRetencion,
  enc.TotalITBISPercepcion,
  enc.TotalISRPercepcion,
  enc.TipoMoneda,
  enc.TipoCambio,
  enc.MontoGravadoTotalOtraMoneda,
  enc.MontoGravado1OtraMoneda,
  enc.MontoGravado2OtraMoneda,
  enc.MontoGravado3OtraMoneda,
  enc.MontoExentoOtraMoneda,
  enc.TotalITBISOtraMoneda,
  enc.TotalITBIS1OtraMoneda,
  enc.TotalITBIS2OtraMoneda,
  enc.TotalITBIS3OtraMoneda,
  enc.MontoImpuestoAdicionalOtraMoneda,
  enc.TipoImpuestoOtraMoneda1,
  enc.TasaImpuestoAdicionalOtraMoneda1,
  enc.MontoImpuestoSelectivoConsumoEspecificoOtraMoneda1,
  enc.MontoImpuestoSelectivoConsumoAdvaloremOtraMoneda1,
  enc.OtrosImpuestosAdicionalesOtraMoneda1,
  enc.TipoImpuestoOtraMoneda2,
  enc.TasaImpuestoAdicionalOtraMoneda2,
  enc.MontoImpuestoSelectivoConsumoEspecificoOtraMoneda2,
  enc.MontoImpuestoSelectivoConsumoAdvaloremOtraMoneda2,
  enc.OtrosImpuestosAdicionalesOtraMoneda2,
  enc.TipoImpuestoOtraMoneda3,
  enc.TasaImpuestoAdicionalOtraMoneda3,
  enc.MontoImpuestoSelectivoConsumoEspecificoOtraMoneda3,
  enc.MontoImpuestoSelectivoConsumoAdvaloremOtraMoneda3,
  enc.OtrosImpuestosAdicionalesOtraMoneda3,
  enc.TipoImpuestoOtraMoneda4,
  enc.TasaImpuestoAdicionalOtraMoneda4,
  enc.MontoImpuestoSelectivoConsumoEspecificoOtraMoneda4,
  enc.MontoImpuestoSelectivoConsumoAdvaloremOtraMoneda4,
  enc.OtrosImpuestosAdicionalesOtraMoneda4,
  enc.MontoTotalOtraMoneda,
  enc.Trackid,
  enc.FechaFirma,
  enc.CodigoSeguridad,
  enc.CodigoSeguridadCF,
  enc.EstadoFiscal,
  enc.fechacreacion,
  enc.EstadoImpresion,
  enc.ConteoImpresiones,
  enc.transferencia,
  enc.Modificado,
  enc.ResultadoEstadoFiscal,
  enc.MontoDGII,
  enc.MontoITBISDGII,
  enc.TipoImpuesto5,
  enc.TasaImpuestoAdicional5,
  enc.MontoImpuestoSelectivoConsumoEspecifico5,
  enc.MontoImpuestoSelectivoConsumoAdvalorem5,
  enc.OtrosImpuestosAdicionales5,
  enc.TipoImpuesto6,
  enc.TasaImpuestoAdicional6,
  enc.MontoImpuestoSelectivoConsumoEspecifico6,
  enc.MontoImpuestoSelectivoConsumoAdvalorem6,
  enc.OtrosImpuestosAdicionales6,
  enc.TipoImpuesto7,
  enc.TasaImpuestoAdicional7,
  enc.MontoImpuestoSelectivoConsumoEspecifico7,
  enc.MontoImpuestoSelectivoConsumoAdvalorem7,
  enc.OtrosImpuestosAdicionales7,
  enc.TipoImpuesto8,
  enc.TasaImpuestoAdicional8,
  enc.MontoImpuestoSelectivoConsumoEspecifico8,
  enc.MontoImpuestoSelectivoConsumoAdvalorem8,
  enc.OtrosImpuestosAdicionales8,
  enc.TipoImpuesto9,
  enc.TasaImpuestoAdicional9,
  enc.MontoImpuestoSelectivoConsumoEspecifico9,
  enc.MontoImpuestoSelectivoConsumoAdvalorem9,
  enc.OtrosImpuestosAdicionales9,
  enc.TipoImpuesto10,
  enc.TasaImpuestoAdicional10,
  enc.MontoImpuestoSelectivoConsumoEspecifico10,
  enc.MontoImpuestoSelectivoConsumoAdvalorem10,
  enc.OtrosImpuestosAdicionales10,
  enc.TipoImpuesto11,
  enc.TasaImpuestoAdicional11,
  enc.MontoImpuestoSelectivoConsumoEspecifico11,
  enc.MontoImpuestoSelectivoConsumoAdvalorem11,
  enc.OtrosImpuestosAdicionales11,
  enc.TipoImpuesto12,
  enc.TasaImpuestoAdicional12,
  enc.MontoImpuestoSelectivoConsumoEspecifico12,
  enc.MontoImpuestoSelectivoConsumoAdvalorem12,
  enc.OtrosImpuestosAdicionales12,
  enc.TipoImpuesto13,
  enc.TasaImpuestoAdicional13,
  enc.MontoImpuestoSelectivoConsumoEspecifico13,
  enc.MontoImpuestoSelectivoConsumoAdvalorem13,
  enc.OtrosImpuestosAdicionales13,
  enc.TipoImpuesto14,
  enc.TasaImpuestoAdicional14,
  enc.MontoImpuestoSelectivoConsumoEspecifico14,
  enc.MontoImpuestoSelectivoConsumoAdvalorem14,
  enc.OtrosImpuestosAdicionales14,
  enc.TipoImpuesto15,
  enc.TasaImpuestoAdicional15,
  enc.MontoImpuestoSelectivoConsumoEspecifico15,
  enc.MontoImpuestoSelectivoConsumoAdvalorem15,
  enc.OtrosImpuestosAdicionales15,
  enc.TipoImpuesto16,
  enc.TasaImpuestoAdicional16,
  enc.MontoImpuestoSelectivoConsumoEspecifico16,
  enc.MontoImpuestoSelectivoConsumoAdvalorem16,
  enc.OtrosImpuestosAdicionales16,
  enc.TipoImpuesto17,
  enc.TasaImpuestoAdicional17,
  enc.MontoImpuestoSelectivoConsumoEspecifico17,
  enc.MontoImpuestoSelectivoConsumoAdvalorem17,
  enc.OtrosImpuestosAdicionales17,
  enc.TipoImpuesto18,
  enc.TasaImpuestoAdicional18,
  enc.MontoImpuestoSelectivoConsumoEspecifico18,
  enc.MontoImpuestoSelectivoConsumoAdvalorem18,
  enc.OtrosImpuestosAdicionales18,
  enc.TipoImpuesto19,
  enc.TasaImpuestoAdicional19,
  enc.MontoImpuestoSelectivoConsumoEspecifico19,
  enc.MontoImpuestoSelectivoConsumoAdvalorem19,
  enc.OtrosImpuestosAdicionales19,
  enc.TipoImpuesto20,
  enc.TasaImpuestoAdicional20,
  enc.MontoImpuestoSelectivoConsumoEspecifico20,
  enc.MontoImpuestoSelectivoConsumoAdvalorem20,
  enc.OtrosImpuestosAdicionales20,
  enc.NumeroLineaDoR1,
  enc.TipoAjuste1,
  enc.IndicadorNorma10071,
  enc.DescripcionDescuentooRecargo1,
  enc.TipoValor1,
  enc.ValorDescuentooRecargo1,
  enc.MontoDescuentooRecargo1,
  enc.MontoDescuentooRecargoOtraMoneda1,
  enc.IndicadorFacturacionDescuentooRecargo1,
  enc.NumeroLineaDoR2,
  enc.TipoAjuste2,
  enc.IndicadorNorma10072,
  enc.DescripcionDescuentooRecargo2,
  enc.TipoValor2,
  enc.ValorDescuentooRecargo2,
  enc.MontoDescuentooRecargo2,
  enc.MontoDescuentooRecargoOtraMoneda2,
  enc.IndicadorFacturacionDescuentooRecargo2,
  enc.NumeroLineaDoR3,
  enc.TipoAjuste3,
  enc.IndicadorNorma10073,
  enc.DescripcionDescuentooRecargo3,
  enc.TipoValor3,
  enc.ValorDescuentooRecargo3,
  enc.MontoDescuentooRecargo3,
  enc.MontoDescuentooRecargoOtraMoneda3,
  enc.IndicadorFacturacionDescuentooRecargo3,
  enc.NumeroLineaDoR4,
  enc.TipoAjuste4,
  enc.IndicadorNorma10074,
  enc.DescripcionDescuentooRecargo4,
  enc.TipoValor4,
  enc.ValorDescuentooRecargo4,
  enc.MontoDescuentooRecargo4,
  enc.MontoDescuentooRecargoOtraMoneda4,
  enc.IndicadorFacturacionDescuentooRecargo4,
  enc.NumeroLineaDoR5,
  enc.TipoAjuste5,
  enc.IndicadorNorma10075,
  enc.DescripcionDescuentooRecargo5,
  enc.TipoValor5,
  enc.ValorDescuentooRecargo5,
  enc.MontoDescuentooRecargo5,
  enc.MontoDescuentooRecargoOtraMoneda5,
  enc.IndicadorFacturacionDescuentooRecargo5,
  enc.NumeroLineaDoR6,
  enc.TipoAjuste6,
  enc.IndicadorNorma10076,
  enc.DescripcionDescuentooRecargo6,
  enc.TipoValor6,
  enc.ValorDescuentooRecargo6,
  enc.MontoDescuentooRecargo6,
  enc.MontoDescuentooRecargoOtraMoneda6,
  enc.IndicadorFacturacionDescuentooRecargo6,
  enc.NumeroLineaDoR7,
  enc.TipoAjuste7,
  enc.IndicadorNorma10077,
  enc.DescripcionDescuentooRecargo7,
  enc.TipoValor7,
  enc.ValorDescuentooRecargo7,
  enc.MontoDescuentooRecargo7,
  enc.MontoDescuentooRecargoOtraMoneda7,
  enc.IndicadorFacturacionDescuentooRecargo7,
  enc.NumeroLineaDoR8,
  enc.TipoAjuste8,
  enc.IndicadorNorma10078,
  enc.DescripcionDescuentooRecargo8,
  enc.TipoValor8,
  enc.ValorDescuentooRecargo8,
  enc.MontoDescuentooRecargo8,
  enc.MontoDescuentooRecargoOtraMoneda8,
  enc.IndicadorFacturacionDescuentooRecargo8,
  enc.NumeroLineaDoR9,
  enc.TipoAjuste9,
  enc.IndicadorNorma10079,
  enc.DescripcionDescuentooRecargo9,
  enc.TipoValor9,
  enc.ValorDescuentooRecargo9,
  enc.MontoDescuentooRecargo9,
  enc.MontoDescuentooRecargoOtraMoneda9,
  enc.IndicadorFacturacionDescuentooRecargo9,
  enc.NumeroLineaDoR10,
  enc.TipoAjuste10,
  enc.IndicadorNorma100710,
  enc.DescripcionDescuentooRecargo10,
  enc.TipoValor10,
  enc.ValorDescuentooRecargo10,
  enc.MontoDescuentooRecargo10,
  enc.MontoDescuentooRecargoOtraMoneda10,
  enc.IndicadorFacturacionDescuentooRecargo10,
  enc.NumeroLineaDoR11,
  enc.TipoAjuste11,
  enc.IndicadorNorma100711,
  enc.DescripcionDescuentooRecargo11,
  enc.TipoValor11,
  enc.ValorDescuentooRecargo11,
  enc.MontoDescuentooRecargo11,
  enc.MontoDescuentooRecargoOtraMoneda11,
  enc.IndicadorFacturacionDescuentooRecargo11,
  enc.NumeroLineaDoR12,
  enc.TipoAjuste12,
  enc.IndicadorNorma100712,
  enc.DescripcionDescuentooRecargo12,
  enc.TipoValor12,
  enc.ValorDescuentooRecargo12,
  enc.MontoDescuentooRecargo12,
  enc.MontoDescuentooRecargoOtraMoneda12,
  enc.IndicadorFacturacionDescuentooRecargo12,
  enc.NumeroLineaDoR13,
  enc.TipoAjuste13,
  enc.IndicadorNorma100713,
  enc.DescripcionDescuentooRecargo13,
  enc.TipoValor13,
  enc.ValorDescuentooRecargo13,
  enc.MontoDescuentooRecargo13,
  enc.MontoDescuentooRecargoOtraMoneda13,
  enc.IndicadorFacturacionDescuentooRecargo13,
  enc.NumeroLineaDoR14,
  enc.TipoAjuste14,
  enc.IndicadorNorma100714,
  enc.DescripcionDescuentooRecargo14,
  enc.TipoValor14,
  enc.ValorDescuentooRecargo14,
  enc.MontoDescuentooRecargo14,
  enc.MontoDescuentooRecargoOtraMoneda14,
  enc.IndicadorFacturacionDescuentooRecargo14,
  enc.NumeroLineaDoR15,
  enc.TipoAjuste15,
  enc.IndicadorNorma100715,
  enc.DescripcionDescuentooRecargo15,
  enc.TipoValor15,
  enc.ValorDescuentooRecargo15,
  enc.MontoDescuentooRecargo15,
  enc.MontoDescuentooRecargoOtraMoneda15,
  enc.IndicadorFacturacionDescuentooRecargo15,
  enc.NumeroLineaDoR16,
  enc.TipoAjuste16,
  enc.IndicadorNorma100716,
  enc.DescripcionDescuentooRecargo16,
  enc.TipoValor16,
  enc.ValorDescuentooRecargo16,
  enc.MontoDescuentooRecargo16,
  enc.MontoDescuentooRecargoOtraMoneda16,
  enc.IndicadorFacturacionDescuentooRecargo16,
  enc.NumeroLineaDoR17,
  enc.TipoAjuste17,
  enc.IndicadorNorma100717,
  enc.DescripcionDescuentooRecargo17,
  enc.TipoValor17,
  enc.ValorDescuentooRecargo17,
  enc.MontoDescuentooRecargo17,
  enc.MontoDescuentooRecargoOtraMoneda17,
  enc.IndicadorFacturacionDescuentooRecargo17,
  enc.NumeroLineaDoR18,
  enc.TipoAjuste18,
  enc.IndicadorNorma100718,
  enc.DescripcionDescuentooRecargo18,
  enc.TipoValor18,
  enc.ValorDescuentooRecargo18,
  enc.MontoDescuentooRecargo18,
  enc.MontoDescuentooRecargoOtraMoneda18,
  enc.IndicadorFacturacionDescuentooRecargo18,
  enc.NumeroLineaDoR19,
  enc.TipoAjuste19,
  enc.IndicadorNorma100719,
  enc.DescripcionDescuentooRecargo19,
  enc.TipoValor19,
  enc.ValorDescuentooRecargo19,
  enc.MontoDescuentooRecargo19,
  enc.MontoDescuentooRecargoOtraMoneda19,
  enc.IndicadorFacturacionDescuentooRecargo19,
  enc.NumeroLineaDoR20,
  enc.TipoAjuste20,
  enc.IndicadorNorma100720,
  enc.DescripcionDescuentooRecargo20,
  enc.TipoValor20,
  enc.ValorDescuentooRecargo20,
  enc.MontoDescuentooRecargo20,
  enc.MontoDescuentooRecargoOtraMoneda20,
  enc.IndicadorFacturacionDescuentooRecargo20,
  enc.NCFModificado,
  enc.RNCOtroContribuyente,
  enc.FechaNCFModificado,
  enc.CodigoModificacion,
  enc.RazonModificacion,
  CASE
        WHEN SUBSTRING(enc.encf, 2, 2) = '32' AND enc.montototal < 250000 
            THEN CONCAT(
                'https://fc.dgii.gov.do', 
                CASE WHEN LEN(TRIM(AI.ruta)) > 0 THEN CONCAT(TRIM(AI.ruta), '/') ELSE '' END,
                'ConsultaTimbreFC?RncEmisor=', TRIM(enc.rncemisor),
                '&ENCF=', TRIM(enc.encf),
                '&MontoTotal=', round(enc.montototal,2),
                '&CodigoSeguridad=', [dbo].[FNCambiaHexadecimal](TRIM(enc.CodigoSeguridad))
            )
        WHEN SUBSTRING(enc.encf, 2, 2) = '47' 
            THEN CONCAT(
                'https://ecf.dgii.gov.do', 
                CASE WHEN LEN(TRIM(AI.ruta)) > 0 THEN CONCAT(TRIM(AI.ruta), '/') ELSE '' END,
                'ConsultaTimbre?RncEmisor=', TRIM(enc.rncemisor),
                '&ENCF=', TRIM(enc.encf),
                '&FechaEmision=', dbo.FNFechaDMY(enc.fechaemision),
                '&MontoTotal=', round(enc.montototal,2),
                '&FechaFirma=', REPLACE(TRIM(enc.fechaFirma), ' ', '%20'),
                '&CodigoSeguridad=', [dbo].[FNCambiaHexadecimal](enc.CodigoSeguridad)
            )
        ELSE 
            CONCAT(
                'https://ecf.dgii.gov.do', 
                CASE WHEN LEN(TRIM(AI.ruta)) > 0 THEN CONCAT(TRIM(AI.ruta), '/') ELSE '' END,
                'ConsultaTimbre?RncEmisor=', TRIM(enc.rncemisor),
			    CONCAT('&RncComprador=', REPLACE(TRIM(enc.rnccomprador), '-', '')),
				'&ENCF=', TRIM(enc.encf),
                '&FechaEmision=', dbo.FNFechaDMY(enc.fechaemision),
                '&MontoTotal=', round(enc.montototal,2),
                '&FechaFirma=', REPLACE(TRIM(enc.FechaFirma), ' ', '%20'),
                '&CodigoSeguridad=', [dbo].[FNCambiaHexadecimal](TRIM(enc.CodigoSeguridad))
            )
    END  AS URLQR 
FROM
  dbo.FEEncabezado as enc
  LEFT OUTER JOIN Totales as Totales  WITH (NOLOCK) on Totales.encf = enc.encf and Totales.rncemisor = enc.rncemisor
  CROSS JOIN AmbienteInfo AS AI  WITH (NOLOCK)
--where enc.encf ='E310000000105'

