create or alter view vFENCDIDEtRD as

    SELECT
    NULL AS NumeroLinea,
    cxc.documento AS NumeroFacturaInterna,
    cxc.tipomovi AS TipoDocumento,
    SUBSTRING (cxc.ncf1, 2, 2) AS TipoECF,
    SUBSTRING (cxc.ncf1, 1, 1) AS TipoECFL,
    cxc.ncf1 AS eNCF,
    cxc.RNCEmisor,
    CAST('' AS CHAR(100)) AS TipoCodigo1,
    CAST('' AS CHAR(100)) AS CodigoItem1,
    CAST('' AS CHAR(100)) AS TipoCodigo2,
    CAST('' AS CHAR(100)) AS CodigoItem2,
    CAST('' AS CHAR(100)) AS TipoCodigo3,
    CAST('' AS CHAR(100)) AS CodigoItem3,
    CAST('' AS CHAR(100)) AS TipoCodigo4,
    CAST('' AS CHAR(100)) AS CodigoItem4,
    CAST('' AS CHAR(100)) AS TipoCodigo5,
    CAST('' AS CHAR(100)) AS CodigoItem5,
    i.codigodgii AS IndicadorFacturacion,
    i.Siglas AS SiglasImpuesto,
    i.Descrip AS DescripcionImpuesto,
    NULL AS IndicadorAgenteRetencionoPercepcion,
    /*cxc.itbisret*/
	NULL AS MontoITBISRetenido,
    /*cxc.isr*/
	NULL AS MontoISRRetenido,
     cxc.concepto as NombreItem,
    1 AS IndicadorBienoServicio,
    NULL AS DescripcionItem,
    1 AS CantidadItem,
    '43' AS UnidadMedida,
	'' as UnidadMedidaL,
    NULL AS CantidadReferencia,
    NULL AS UnidadReferencia,
    NULL AS Subcantidad1,
    NULL AS CodigoSubcantidad1,
    NULL AS Subcantidad2,
    NULL AS CodigoSubcantidad2,
    NULL AS Subcantidad3,
    NULL AS CodigoSubcantidad3,
    NULL AS Subcantidad4,
    NULL AS CodigoSubcantidad4,
    NULL AS Subcantidad5,
    NULL AS CodigoSubcantidad5,
    NULL AS GradosAlcohol,
    NULL AS PrecioUnitarioReferencia,
    NULL AS FechaElaboracion,
    NULL AS FechaVencimientoItem,
    NULL AS PesoNetoKilogramo,
    NULL AS PesoNetoMineria,
    NULL AS TipoAfiliacion,
    NULL AS Liquidacion,
    cxc.monto AS PrecioUnitarioItem,
    cxc.descuen AS DescuentoMonto,
    18 AS TasaITBIS,
    1 AS IndicadorMontoGravado,
    cxc.impuesto AS MontoITBIS,
    NULL AS TasaDescuento,
    (CASE WHEN ISNULL(cxc.descuen,0) <> 0 THEN '$' ELSE '' END) AS TipoSubDescuento1,
    NULL AS SubDescuentoPorcentaje1,
    (CASE WHEN ISNULL(cxc.descuen,0) <> 0 THEN cxc.descuen ELSE NULL END) AS MontoSubDescuento1,
    NULL AS TipoSubDescuento2,
    NULL AS SubDescuentoPorcentaje2,
    NULL AS MontoSubDescuento2,
    NULL AS TipoSubDescuento3,
    NULL AS SubDescuentoPorcentaje3,
    NULL AS MontoSubDescuento3,
    NULL AS TipoSubDescuento4,
    NULL AS SubDescuentoPorcentaje4,
    NULL AS MontoSubDescuento4,
    NULL AS TipoSubDescuento5,
    NULL AS SubDescuentoPorcentaje5,
    NULL AS MontoSubDescuento5,
    NULL AS MontoRecargo,
    NULL AS TipoSubRecargo1,
    NULL AS SubRecargoPorcentaje1,
    NULL AS MontoSubRecargo1,
    NULL AS TipoSubRecargo2,
    NULL AS SubRecargoPorcentaje2,
    NULL AS MontoSubRecargo2,
    NULL AS TipoSubRecargo3,
    NULL AS SubRecargoPorcentaje3,
    NULL AS MontoSubRecargo3,
    NULL AS TipoSubRecargo4,
    NULL AS SubRecargoPorcentaje4,
    NULL AS MontoSubRecargo4,
    NULL AS TipoSubRecargo5,
    NULL AS SubRecargoPorcentaje5,
    NULL AS MontoSubRecargo5,
    NULL AS TipoImpuesto1,
    NULL AS TipoImpuesto2,
    CASE
     WHEN COALESCE(cxc.tasa, 1.00) = 0 THEN 1 --SI ES CERO DEVIELVE 1
     WHEN COALESCE(cxc.tasa, 1.00) > 1 THEN cxc.tasa -- SI ES MAYOR QUE UNO DEVUELVE ;A TASA 
     ELSE COALESCE(cxc.tasa, 1.00) -- SI ES NULO DEVUELVE 1
    END
    AS TipoCambio,
    NULL AS MontoITBISOtraMoneda,
    NULL AS PrecioOtraMoneda,
    NULL AS DescuentoOtraMoneda,
    NULL AS MontoRecargoOtraMoneta,
    NULL AS MontoItemOtraMoneda,
    cxc.monto AS MontoItem,
	'' AS NotaImpresion

FROM
    cxcmovi1 cxc
    LEFT OUTER JOIN dbo.impuesto AS i ON i.impuesto = '00'
WHERE
    (cxc.tipomovi IN ('02'))
and (COALESCE(cxc.tasa, 1.00) =1 OR COALESCE(cxc.tasa, 1.00) = 0)
AND (cxc.ncf1 IS NOT NULL) 
AND (cxc.ncf1 <> '') 
AND (cxc.EstadoFiscal IS NOT NULL)

