
--create or alter view vFEEncabezadoCajachica as

--Caja Chica
SELECT	
    
    MAX(cc.documento) as NumeroFacturaInterna,
    MAX(cc.ncftipo) as TipoDocumento,
    MAX(SUBSTRING(cc.ncf, 1, 1)) as TipoECFL,
    MAX(SUBSTRING(cc.ncf, 2, 2)) as TipoECF,
    MAX(tn.Descripcion) as TipoECFL1,
    MAX(tn.Descripcion) as Descripcion,
    MAX(tn.Auxiliar) as Auxiliar,
    'CAJACHICA' as Tabla,
    MAX(cc.campo1) as campo1,
    MAX(cc.campo2) as campo2,
	cc.ncf AS eNCF,
    MAX(cc.FVencimientoNCF) as FechaVencimientoSecuencia,
    NULL as FechaLimitePago,
    0 as TerminoPagoN,
    CAST('' AS CHAR(100)) as TerminoPago,
    '0'as Almacen,
    0 as IndicadorNotaCredito,
    0 as IndicadorMontoGravado,
    '01' as TipoIngresos,
    1 as TipoPago,
    'CONTADO' as TipoPagoL,
    NULL as TipoCuentaPago,
    NULL as NumeroCuentaPago,
    NULL as BancoPago,
    NULL as FechaDesde,
    NULL as FechaHasta,
    NULL as TotalPaginas,
	REPLACE(cc.RNCEmisor, '-', '') AS RNCEmisor,

  MAX(e.TipodeIngresos) AS TipodeIngresos,
  MAX(e.IndicadorEnvioDiferido) AS IndicadorEnvioDiferido,
  --Emisor
  MAX(e.nombre) as RazonSocialEmisor,
  CAST('' AS CHAR(1)) AS NombreComercial,
  CAST('' AS CHAR(1)) AS Sucursal,
  MAX(e.dire) as DireccionEmisor,
  CAST('' AS CHAR(1)) AS Municipio,
  CAST('' AS CHAR(1)) AS Provincia,
  CAST('' AS CHAR(1)) as CorreoEmisor,
  CAST('' AS CHAR(1)) as WebSite,
  CAST('' AS CHAR(1)) as ActividadEconomica,
  MAX(e.Tele)  AS TelefonoEmisor1,
    CAST('' AS CHAR(100)) as TelefonoEmisor2,
    CAST('' AS CHAR(100)) as TelefonoEmisor3,
    CAST('' AS CHAR(100)) as CodigoVendedor,
    CAST('' AS CHAR(100)) as NumeroPedidoInterno,
    CAST('' AS CHAR(100)) as ZonaVenta,
    CAST('' AS CHAR(100)) as RutaVenta,
    CAST('' AS CHAR(100)) as InformacionAdicionalEmisor,
    MAX(cc.fecha) as FechaEmision,
    CAST('' AS CHAR(100)) as RNCComprador,
    null as IdentificadorExtranjero,
    CAST('' AS CHAR(100)) as RazonSocialComprador,
    CAST('' AS CHAR(100)) as ContactoComprador,
    CAST('' AS CHAR(100)) as CorreoComprador,
    CAST('' AS CHAR(100)) as DireccionComprador,
    CAST('' AS CHAR(100)) AS MunicipioComprador, 
    CAST('' AS CHAR(100)) as ProvinciaComprador,
    CAST('' AS CHAR(100)) as PaisComprador,
    null as FechaEntrega,
    CAST('' AS CHAR(100)) as ContactoEntrega,
    CAST('' AS CHAR(100)) as DireccionEntrega,
    CAST('' AS CHAR(100)) as TelefonoAdicional,
    null as FechaOrdenCompra,
    CAST('' AS CHAR(100)) as NumeroOrdenCompra,
    CAST('' AS CHAR(100)) as CodigoInternoComprador,
    CAST('' AS CHAR(100)) as ResponsablePago,
    CAST('' AS CHAR(100)) as Informacionadicionalcomprador,
    null as FechaEmbarque,
    CAST('' AS CHAR(100)) as NumeroEmbarque,
    CAST('' AS CHAR(100)) as NumeroContenedor,
    CAST('' AS CHAR(100)) as NumeroReferencia,
    CAST('' AS CHAR(100)) as NombrePuertoEmbarque,
    CAST('' AS CHAR(100)) as CondicionesEntrega,
    NULL as TotalFob,
    NULL as Seguro,
    NULL as Flete,
    NULL as OtrosGastos,
    NULL as TotalCif,
    NULL as RegimenAduanero,
    NULL as NombrePuertoSalida,
    NULL as NombrePuertoDesembarque,
    NULL as PesoBruto,
    NULL as PesoNeto,
    NULL as UnidadPesoBruto,
    NULL as UnidadPesoNeto,
    NULL as CantidadBulto,
    NULL as UnidadBulto,
    NULL as VolumenBulto,
    NULL as UnidadVolumen,
    NULL as ViaTransporte,
    NULL as PaisOrigen,
    NULL as DireccionDestino,
    NULL as PaisDestino,
    NULL as RNCIdentificacionCompaniaTransportista,
    NULL as NombreCompaniaTransportista,
    NULL as NumeroViaje,
    NULL as Conductor,
    NULL as DocumentoTransporte,
    NULL as Ficha,
    NULL as Placa,
    NULL as RutaTransporte,
    NULL as ZonaTransporte,
    NULL as NumeroAlbaran,
    NULL as MontoGravadoTotal,
    NULL as MontoGravadoI1,
    NULL as MontoGravadoI2,
    NULL as MontoGravadoI3,
    SUM(cc.debito - cc.credito) as MontoExento,
    NULL as ITBIS1,
    NULL as ITBIS2,
    0 as ITBIS3,
    NULL as TotalITBIS,
    NULL as TotalITBIS1,
    NULL as TotalITBIS2,
    0 as TotalITBIS3,
    0 as IndicadorMontoGravadoI18,
    0 as IndicadorMontoGravadoI16,
    1 as IndicadorMontoGravadoI0,
    NULL as MontoImpuestoAdicional,
    '' as NombreVendedor,
    SUM(cc.debito - cc.credito) as MontoTotal,
    NULL as MontoNoFacturable,
    NULL as MontoPeriodo,
    NULL as SaldoAnterior,
    NULL as MontoAvancePago,
    NULL as MontoPago,
    NULL as ValorPagar,
    NULL as TotalITBISRetenido,
    NULL as TotalISRRetencion,
    NULL as TotalITBISPercepcion,
	NULL as TotalISRPercepcion,
    'DOP' as TipoMoneda,
    'PESO DOMINICANO' as TipoMonedaL,
    1 as TipoCambio,
    NULL as MontoGravadoTotalOtraMoneda,
    NULL as MontoGravado1OtraMoneda,
    NULL as MontoGravado2OtraMoneda,
    NULL as MontoGravado3OtraMoneda,
    NULL as MontoExentoOtraMoneda,
    NULL as TotalITBISOtraMoneda,
    NULL as TotalITBIS1OtraMoneda,
    NULL as TotalITBIS2OtraMoneda,
    NULL as TotalITBIS3OtraMoneda,
    NULL as MontoImpuestoAdicionalOtraMoneda,
    NULL as MontoTotalOtraMoneda,

  -- Sesion de Nota de credito
  --NCF de la factura que se le esta aplicando la NC
  CAST('' AS CHAR(1)) AS NCFModificado,
  --RNC del NCF afectado
  CAST('' AS CHAR(1)) as RNCOtroContribuyente,
  --Fecha de la factura que se le esta aplicando la NC
  null AS FechaNCFModificado,
  --Razon de modificacion de la factura que se le esta aplicando la NC (Segun tabla DGII)
  --3: Corrige montos del NCF modificado
  NULL AS CodigoModificacion,
  --Numero de de la factura que se le esta aplicando la NC
  CAST('' AS CHAR(1)) AS NumeroDocumentoNCFModificado,
  --Monto de la factura que se le esta aplicando la NC
  0 AS MontoNCFModificado,
  --Abono a la factura que se le esta aplicando la NC (valor de la nota de credito)
  0 AS AbonoNCFModificado,
  --Monto de descuento a la factura que se le esta aplicando la NC
  0 AS DescuentoNCFModificado,
  --Monto Pendinete de la factura que se le esta aplicando la NC
  0 AS PendienteNCFModificado,
  --Razon de Modficiacion especificada por el usurio de la factura que se le esta aplicando la NC en el sistema
  --En caso de que sea una nota de credito, enviar la razon de la modificacion 
 CAST('' AS CHAR(1)) AS RazonModificacion,

  --Datos de Facturacion Electronica	


    MAX(cc.fechacreacion) as fechacreacion,
    MAX(cc.Trackid) as Trackid,
    MAX(cc.FechaFirma) as FechaFirma,
    MAX(cc.CodigoSeguridad) as CodigoSeguridad,
    '' as CodigoSeguridadCF,
    MAX(cc.Estadoimpresion) as EstadoImpresion,
    NULL as ConteoImpresiones,
    MAX(cc.EstadoFiscal) as EstadoFiscal,
    MAX(CONCAT(
        'https://ecf.dgii.gov.do/ecf/ConsultaTimbre?',
        'RncEmisor=', TRIM(cc.rncemisor),
        '&ENCF=', TRIM(cc.ncf),
        '&FechaEmision=', dbo.FNFechaDMY(cc.fecha),
        '&MontoTotal=', (cc.debito - cc.credito),
        '&FechaFirma=', REPLACE(TRIM(cc.FechaFirma), ' ', '%20'),
        '&CodigoSeguridad=', [dbo].[FNCambiaHexadecimal](trim(cc.CodigoSeguridad))
    )) as URLQR,
    max(cc.recibido) as Observaciones,
    '' as Creadopor,
    '' as ModificadoPor,
    max(cc.BENeFICIARIO) as NotaPermanente,
  '' as NotaPago
FROM dbo.cajachica AS cc  WITH (NOLOCK)
LEFT OUTER JOIN dbo.sis_TipoNCF AS tn ON tn.Codigo = SUBSTRING(cc.ncf, 2, 2) 
LEFT OUTER JOIN dbo.empresa AS e ON cc.RNCEmisor = e.rnc 
WHERE cc.ncftipo IN ('GM') AND NCF= 'B1300000129'
AND (cc.ncf IS NOT NULL) 
AND (cc.ncf <> '') 
AND (cc.EstadoFiscal IS NOT NULL)
--AND (SUBSTRING(cc.ncf, 1, 3)) ='E43'
 
GROUP BY cc.ncf, cc.RNCEmisor

